//! Self-registering Start Menu entry on Windows.
//!
//! The MSI creates its own Start Menu shortcut (see `wix/main.wxs`), because
//! MSI has a Shortcut table and that file is checked in and hand-edited. Every
//! other way of getting sicompass onto Windows produces no shortcut at all:
//! `sicompass-installer.ps1` is generated by cargo-dist at release time from a
//! template built for command-line tools, it is not checked in, and it copies
//! binaries and edits PATH and nothing else. The plain `.zip` and
//! `cargo install` are the same story.
//!
//! That left the app reachable only from a terminal unless you happened to
//! pick the MSI, which is backwards for a keyboard-first accessibility tool.
//! So the app registers itself: on startup it makes sure a per-user Start Menu
//! shortcut pointing at the running executable exists. That covers the
//! PowerShell installer, the archive and `cargo install` in one place, with no
//! second installer to maintain.
//!
//! Deliberately *not* done here:
//!
//! - **Anything under Program Files.** That is an MSI install, which already
//!   owns a per-machine shortcut. Adding a per-user one would show the app
//!   twice in the Start Menu.
//! - **Debug builds.** Otherwise every `cargo run` would advertise
//!   `target/debug/sicompass.exe` in the developer's Start Menu.
//! - **Removal.** The MSI uninstalls its own shortcut. This one is left
//!   behind, the same way a stale `.lnk` from any portable app is, because
//!   deleting it would mean a Start Menu write from an app that may simply be
//!   moving to a new install path.
//!
//! Set `SICOMPASS_NO_START_MENU=1` to skip it entirely.
//!
//! On every non-Windows platform this module compiles to a no-op. Linux ships
//! `assets/sicompass.desktop` in the `.deb`, `.rpm` and AppImage, and macOS
//! puts the `.app` in `/Applications`, so neither needs it.

use std::path::{Path, PathBuf};

/// Environment variable that disables Start Menu registration.
pub const NO_START_MENU_ENV: &str = "SICOMPASS_NO_START_MENU";

/// Shortcut file name, without the `.lnk` extension.
///
/// Must stay identical to the `Name` on the `Shortcut` element in
/// `wix/main.wxs`. The two shortcuts are mutually exclusive in practice (see
/// the Program Files rule above), but if a user ever manages to have both, one
/// name means one Start Menu entry rather than two that look unrelated.
///
/// The `(sicompass)` is load-bearing. Start Menu search matches word prefixes,
/// so `Silicon's Compass` alone cannot be found by typing `sicompass`, which is
/// what the binary and every package call it.
pub const SHORTCUT_NAME: &str = "Silicon's Compass (sicompass)";

/// Create the Start Menu shortcut if it is missing, on a background thread.
///
/// Never blocks startup and never fails loudly: a missing Start Menu entry is
/// a papercut, not a reason to interrupt someone launching the app. Failures
/// go to the rolling log.
pub fn spawn_registration() {
    #[cfg(target_os = "windows")]
    {
        // Its own thread so it gets its own COM apartment, which keeps
        // `CoInitializeEx` here from interfering with whatever SDL does on the
        // main thread.
        let _ = std::thread::Builder::new()
            .name("sicompass-start-menu".into())
            .spawn(|| match register() {
                Ok(Some(path)) => tracing::info!("created Start Menu entry at {}", path.display()),
                Ok(None) => tracing::debug!("Start Menu entry not needed"),
                Err(e) => tracing::warn!("could not create Start Menu entry: {e}"),
            });
    }
}

/// Why registration was skipped, or that it should go ahead.
///
/// Split out from the platform code so the policy is testable without a
/// registry, a Start Menu or a real executable.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Decision {
    /// Write the shortcut.
    Install,
    /// `SICOMPASS_NO_START_MENU` is set.
    Disabled,
    /// A development build. See the module docs.
    DebugBuild,
    /// Installed by the MSI, which owns a per-machine shortcut already.
    ManagedByInstaller,
    /// The shortcut is already there.
    AlreadyPresent,
}

/// Decide whether to write the shortcut.
///
/// `program_files` is the list of Program Files roots to treat as
/// installer-managed, passed in rather than read from the environment so the
/// tests can supply their own.
pub fn decide(
    exe: &Path,
    program_files: &[PathBuf],
    shortcut_exists: bool,
    disabled: bool,
    debug_build: bool,
) -> Decision {
    if disabled {
        return Decision::Disabled;
    }
    if debug_build {
        return Decision::DebugBuild;
    }
    if program_files.iter().any(|root| exe.starts_with(root)) {
        return Decision::ManagedByInstaller;
    }
    if shortcut_exists {
        return Decision::AlreadyPresent;
    }
    Decision::Install
}

/// The per-user Start Menu `Programs` directory.
///
/// `%APPDATA%\Microsoft\Windows\Start Menu\Programs`. Per-user rather than
/// per-machine because the PowerShell installer runs unelevated, so this is the
/// only location writable without a UAC prompt the user did not ask for.
pub fn programs_dir(appdata: &Path) -> PathBuf {
    appdata.join("Microsoft/Windows/Start Menu/Programs")
}

/// Full path of the shortcut inside `programs`.
pub fn shortcut_path(programs: &Path) -> PathBuf {
    programs.join(format!("{SHORTCUT_NAME}.lnk"))
}

#[cfg(target_os = "windows")]
mod imp {
    use super::*;
    use std::io;

    use windows::core::{Interface, HSTRING};
    use windows::Win32::System::Com::{
        CoCreateInstance, CoInitializeEx, CoUninitialize, IPersistFile, CLSCTX_INPROC_SERVER,
        COINIT_APARTMENTTHREADED,
    };
    use windows::Win32::UI::Shell::{IShellLinkW, ShellLink};

    /// Create the shortcut if [`decide`] says to.
    ///
    /// Returns the path written, or `None` when nothing needed doing.
    ///
    /// This reads the environment and hands off to [`register_at`], which holds
    /// the actual work. The split is what lets the tests drive the whole path,
    /// COM call included, against a throwaway Start Menu, instead of stopping
    /// at the policy in [`decide`].
    pub fn register() -> io::Result<Option<PathBuf>> {
        let exe = std::env::current_exe()?;
        let appdata =
            std::env::var_os("APPDATA").ok_or_else(|| io::Error::other("APPDATA is not set"))?;

        register_at(
            &exe,
            Path::new(&appdata),
            &program_files_roots(),
            std::env::var_os(NO_START_MENU_ENV).is_some(),
            cfg!(debug_assertions),
        )
    }

    /// [`register`] with every environment input passed in explicitly.
    pub(super) fn register_at(
        exe: &Path,
        appdata: &Path,
        program_files: &[PathBuf],
        disabled: bool,
        debug_build: bool,
    ) -> io::Result<Option<PathBuf>> {
        let target = shortcut_path(&programs_dir(appdata));

        let decision = decide(exe, program_files, target.exists(), disabled, debug_build);
        if decision != Decision::Install {
            tracing::debug!("skipping Start Menu registration: {decision:?}");
            return Ok(None);
        }

        // The installer may have dropped the binary somewhere the Start Menu
        // tree does not exist yet under a fresh profile.
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)?;
        }

        write_link(exe, &target)?;
        Ok(Some(target))
    }

    /// Program Files roots, in both the 64-bit and 32-bit spellings.
    ///
    /// The MSI installs to `ProgramFiles64Folder`, but a 32-bit install of an
    /// older build could sit in the other one, and neither variable is
    /// guaranteed to be set.
    fn program_files_roots() -> Vec<PathBuf> {
        ["ProgramFiles", "ProgramFiles(x86)", "ProgramW6432"]
            .iter()
            .filter_map(std::env::var_os)
            .map(PathBuf::from)
            .collect()
    }

    /// Write a `.lnk` at `link` pointing at `exe`, via the shell's own
    /// `IShellLink`.
    ///
    /// No icon is set. The executable already carries the application icon,
    /// embedded by `build.rs` through `winresource`, and Explorer falls back to
    /// the target's icon when the shortcut names none. That matters: the
    /// PowerShell installer copies binaries only, so `assets/icons/` is not
    /// present in that install and pointing at a file there would give a blank
    /// Start Menu tile.
    pub(super) fn write_link(exe: &Path, link: &Path) -> io::Result<()> {
        // SAFETY: a COM apartment for this thread only, torn down by the guard
        // below on every path out of this function.
        unsafe { CoInitializeEx(None, COINIT_APARTMENTTHREADED) }
            .ok()
            .map_err(io::Error::other)?;
        let _com = ComGuard;

        let result = (|| -> windows::core::Result<()> {
            // SAFETY: all four calls are on an interface we just created on
            // this thread, with in-scope arguments that outlive each call.
            unsafe {
                let shell_link: IShellLinkW =
                    CoCreateInstance(&ShellLink, None, CLSCTX_INPROC_SERVER)?;
                shell_link.SetPath(&HSTRING::from(exe))?;
                if let Some(dir) = exe.parent() {
                    shell_link.SetWorkingDirectory(&HSTRING::from(dir))?;
                }
                shell_link
                    .SetDescription(&HSTRING::from("Use your whole computer from the keyboard"))?;
                shell_link
                    .cast::<IPersistFile>()?
                    .Save(&HSTRING::from(link), true)?;
            }
            Ok(())
        })();

        result.map_err(io::Error::other)
    }

    /// Balances the `CoInitializeEx` above even if a `?` returns early.
    struct ComGuard;

    impl Drop for ComGuard {
        fn drop(&mut self) {
            // SAFETY: pairs with the CoInitializeEx that created this guard,
            // on the same thread.
            unsafe { CoUninitialize() };
        }
    }
}

#[cfg(target_os = "windows")]
pub use imp::register;

#[cfg(test)]
mod tests {
    use super::*;

    /// A `C:\`-rooted path, assembled from components so the separators are
    /// the host's.
    ///
    /// The layouts below are Windows ones, but [`decide`] is compiled on every
    /// platform and so are these tests. A backslash is an ordinary character
    /// on Unix, so `Path::new(r"C:\Program Files\sicompass\bin\sicompass.exe")`
    /// is one opaque component there and the `starts_with` in [`decide`] can
    /// never match, whatever the policy says. Joining component by component
    /// gives a real rooted path on Windows and an equivalent one everywhere
    /// else, which keeps the Program Files rule under test on all four CI
    /// runners rather than only the Windows one.
    fn win(parts: &[&str]) -> PathBuf {
        let mut path = PathBuf::from(r"C:\");
        path.extend(parts);
        path
    }

    fn pf() -> Vec<PathBuf> {
        vec![win(&["Program Files"])]
    }

    #[test]
    fn installs_for_a_release_build_outside_program_files() {
        let exe = win(&["Users", "a", ".cargo", "bin", "sicompass.exe"]);
        assert_eq!(decide(&exe, &pf(), false, false, false), Decision::Install);
    }

    /// The whole point of the module: the PowerShell installer's layout has to
    /// be the case that gets a shortcut.
    #[test]
    fn installs_for_the_powershell_installer_layout() {
        let exe = win(&[
            "Users",
            "a",
            "AppData",
            "Local",
            "sicompass",
            "bin",
            "sicompass.exe",
        ]);
        assert_eq!(decide(&exe, &pf(), false, false, false), Decision::Install);
    }

    /// An MSI install already has a per-machine shortcut. A second, per-user
    /// one would show the app twice.
    #[test]
    fn skips_when_installed_under_program_files() {
        let exe = win(&["Program Files", "sicompass", "bin", "sicompass.exe"]);
        assert_eq!(
            decide(&exe, &pf(), false, false, false),
            Decision::ManagedByInstaller
        );
    }

    #[test]
    fn skips_when_the_shortcut_is_already_there() {
        let exe = win(&["Users", "a", ".cargo", "bin", "sicompass.exe"]);
        assert_eq!(
            decide(&exe, &pf(), true, false, false),
            Decision::AlreadyPresent
        );
    }

    #[test]
    fn skips_debug_builds_so_cargo_run_stays_invisible() {
        let exe = win(&["sicompass", "target", "debug", "sicompass.exe"]);
        assert_eq!(
            decide(&exe, &pf(), false, false, true),
            Decision::DebugBuild
        );
    }

    /// The opt-out has to win over everything, including a missing shortcut in
    /// an otherwise perfectly installable layout.
    #[test]
    fn the_env_var_wins_over_every_other_condition() {
        let exe = win(&["Users", "a", ".cargo", "bin", "sicompass.exe"]);
        assert_eq!(decide(&exe, &pf(), false, true, false), Decision::Disabled);
    }

    #[test]
    fn shortcut_name_matches_the_one_in_the_wix_template() {
        // Guards the pairing documented on SHORTCUT_NAME: if someone renames
        // the shortcut in main.wxs, this catches the half-done rename.
        let wxs = include_str!("../wix/main.wxs");
        assert!(
            wxs.contains(&format!("Name=\"{SHORTCUT_NAME}\"")),
            "wix/main.wxs no longer declares a shortcut named {SHORTCUT_NAME:?}"
        );
    }

    #[test]
    fn shortcut_name_is_findable_by_typing_the_binary_name() {
        // Start Menu search matches word prefixes, so the binary name has to
        // start a word of its own.
        assert!(
            SHORTCUT_NAME
                .split(|c: char| !c.is_alphanumeric())
                .any(|word| word == "sicompass"),
            "{SHORTCUT_NAME:?} cannot be found by typing `sicompass`"
        );
    }

    #[test]
    fn shortcut_lands_in_the_per_user_programs_directory() {
        let path = shortcut_path(&programs_dir(&win(&["Users", "a", "AppData", "Roaming"])));
        assert!(path.ends_with(format!("{SHORTCUT_NAME}.lnk")));
        assert!(path.to_string_lossy().contains("Start Menu"));
    }

    #[cfg(target_os = "windows")]
    fn temp_dir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "sicompass-lnk-{tag}-{}-{}",
            std::process::id(),
            line!()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    /// Exercises the real shell API, not just the policy above.
    #[cfg(target_os = "windows")]
    #[test]
    fn writes_a_real_shortcut_file() {
        let dir = temp_dir("write");
        let link = shortcut_path(&dir);
        let exe = std::env::current_exe().unwrap();

        super::imp::write_link(&exe, &link).expect("failed to write shortcut");
        assert!(link.is_file(), "no .lnk at {}", link.display());
        assert!(
            std::fs::metadata(&link).unwrap().len() > 0,
            "shortcut file is empty"
        );

        std::fs::remove_dir_all(&dir).ok();
    }

    /// The whole path a real install takes, against a throwaway Start Menu:
    /// build the directory tree, decide, write the `.lnk`, and report where.
    #[cfg(target_os = "windows")]
    #[test]
    fn registers_into_an_empty_start_menu_then_leaves_it_alone() {
        let appdata = temp_dir("register");
        let exe = std::env::current_exe().unwrap();

        // First run: nothing exists yet, not even the Programs directory.
        let written = super::imp::register_at(&exe, &appdata, &[], false, false)
            .expect("registration failed")
            .expect("registration reported nothing to do");

        assert!(written.is_file(), "no .lnk at {}", written.display());
        assert_eq!(written, shortcut_path(&programs_dir(&appdata)));

        // Second run must be a no-op rather than a rewrite, so launching the
        // app does not fight a shortcut the user moved or renamed.
        let again = super::imp::register_at(&exe, &appdata, &[], false, false)
            .expect("second registration failed");
        assert_eq!(again, None, "registration was not idempotent");

        std::fs::remove_dir_all(&appdata).ok();
    }

    /// An MSI install must not also get a per-user shortcut, checked through
    /// the real entry point rather than only through [`decide`].
    #[cfg(target_os = "windows")]
    #[test]
    fn registers_nothing_for_an_install_under_program_files() {
        let appdata = temp_dir("msi");
        let program_files = win(&["Program Files"]);
        let exe = program_files.join(r"sicompass\bin\sicompass.exe");

        let result = super::imp::register_at(&exe, &appdata, &[program_files], false, false)
            .expect("registration failed");

        assert_eq!(result, None);
        assert!(
            !shortcut_path(&programs_dir(&appdata)).exists(),
            "wrote a duplicate shortcut for an MSI install"
        );

        std::fs::remove_dir_all(&appdata).ok();
    }
}
